//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Msc-generator.rc
//
#define IDR_SRVR_INPLACE                4
#define IDR_TOOLBAR_SRVR_INPLACE        4
#define IDR_SRVR_INPLACE_256            5
#define IDR_SRVR_EMBEDDED               6
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define IDS_TOOLBAR_DESIGN              126
#define IDR_MAINFRAME                   128
#define IDR_TOOLBAR_MAINFRAME           128
#define IDR_MAINFRAME_256               129
#define IDR_TOOLBAR_MAINFRAME_256       129
#define IDR_SigChartTYPE                130
#define IDD_DIALOG_OPTIONS              132
#define IDD_PROGRESSDIALOG              135
#define IDD_ABOUTBOX                    136
#define IDR_THEME_MENU                  200
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_VS_2008         219
#define ID_VIEW_APPLOOK_WINDOWS_7       220
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDR_DESIGNBAR                   310
#define IDD_POPUPLIST                   311
#define IDR_SRVR_INPLACE_257            311
#define IDD_DIALOG_VERSION              313
#define IDR_HTML1                       314
#define IDD_DIALOG1                     315
#define IDD_SCALE                       315
#define IDB_PREFLARGE                   317
#define IDB_PREFSMALL                   318
#define IDC_RADIO1                      1000
#define IDC_EDIT1                       1001
#define IDC_BUTTON_URL                  1001
#define IDC_EDIT2                       1002
#define IDC_BUTTON_LATEST_URL           1002
#define IDC_CHECK_PEDANTIC              1003
#define IDC_EDIT3                       1003
#define IDC_CHECK_WARNINGS              1004
#define IDC_RADIO2                      1005
#define IDC_RADIO3                      1006
#define IDC_EDIT_DEFAULT_TEXT           1007
#define IDC_RADIO_SCALING_Y             1007
#define IDC_OUTPUT_LIST                 1008
#define IDC_CHECK_ALWAYSOPEN            1008
#define IDC_CHECK_PB_EDITING            1009
#define IDC_INTERNAL_EDITOR             1009
#define IDC_CHECK_PB_EMBEDDED           1010
#define IDC_CHECK_CSH                   1011
#define IDC_CHECK_SMART_IDENT           1012
#define IDC_COMBO_CSH                   1013
#define IDC_BUTTON_URL2                 1014
#define IDC_CHECK_HINTS                 1014
#define IDC_STATIC_VERSION              1015
#define IDC_CHECK_SMART_HINT_ENTITY     1015
#define IDC_STATIC_CURRENT_VERSION      1016
#define IDC_CHECK_SMART_HINT_ATTR_NAME  1016
#define IDC_STATIC_LATEST_VERSION       1017
#define IDC_CHECK_SMART_HINT_ATTR_VALUE 1017
#define IDC_CHECK_SMART_HINT_LINE_START 1018
#define IDC_LIST1                       1019
#define IDC_CHECK_SMART_HINT_COMPACT    1019
#define IDC_LIST2                       1020
#define IDC_CHECK_SMART_HINT_COMPACT2   1020
#define IDC_CHECK_SMART_HINT_FILTER     1020
#define IDC_CHECK_CSH_ERRORS            1021
#define IDC_CHECK_CSH_ERROR             1021
#define IDC_RADIO_SCALING_NO            1021
#define IDC_CHECK_CSH_ERROR_IN_WINDOW   1022
#define IDC_RADIO_SCALING_XY            1022
#define IDC_BUTTON_SCALE                1023
#define IDC_EDIT_SCALE                  1023
#define IDC_EDIT_X                      1024
#define IDC_EDIT_Y                      1025
#define IDC_EDIT_XY_X                   1026
#define IDC_EDIT_XY_Y                   1027
#define IDC_STATIC_ORIGINAL_SIZE        1028
#define IDC_RADIO_SCALING_SCALE         1029
#define IDC_RADIO_SCALING_X             1030
#define IDC_STATIC_LATEST               1031
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_FILE_EXPORT                  32771
#define ID_BUTTON_EDITTEXT              32772
#define ID_EDIT_PREFERENCES             32773
#define ID_VIEW_ZOOMIN                  32775
#define ID_VIEW_ZOOMOUT                 32776
#define ID_VIEW_ADJUSTWIDTH             32777
#define ID_VIEW_FITTOWIDTH              32778
#define ID_ZOOMMODE_KEEPINOVERVIEW      32779
#define ID_ZOOMMODE_KEEPADJUSTINGWINDOWWIDTH 32780
#define ID_ZOOMMODE_KEEPFITTINGTOWIDTH  32781
#define ID_VIEW_REDRAW                  32782
#define ID_VIEW_ZOOMNORMALIZE           32783
#define ID_DESIGN_PAGE                  32784
#define ID_DESIGN_ZOOM                  32788
#define ID_DESIGN_DESIGN                32789
#define ID_VIEW_RESETASPECTRATIO_INPLACE 32790
#define ID_VIEW_CUSTOMIZE               32791
#define ID_VIEW_EDITOR                  32804
#define ID_EDIT_UPDATE                  32807
#define ID_VIEW_NEXTERROR               32814
#define ID_EDIT_COPYENTIRECHART         32820
#define ID_EDIT_PASETENTIRECHART        32821
#define ID_BUTTON_TRACK                 32826
#define ID_VIEW_FULLSCREEN              32846
#define ID_VIEW_FULL_SCREEN             32847
#define ID_HELP_HELP                    32851
#define ID_VIEW_PREVERROR               32856
#define ID_VIEW_GOTOPREVIOUSERROR       32859
#define ID_BUTTON_AUTO_SPLIT            32860
#define ID_BUTTON_AUT                   32861
#define ID_VIEW_SHOWELEMENTCONTROLS     32864
#define ID_BUTTON_DEFAULT_TEXT          32898
#define ID_EXTERNAL_EDITOR_COMBO        32924
#define ID_DESIGN_PAGE_FULL_SCREEN_NEXT 32925
#define ID_DESIGN_PAGE_FULL_SCREEN_PREV 32926
#define ID_CHECK_EE_NOTEPAD             32935
#define ID_CHECK_EE_NOTEPADPP           32937
#define ID_CHECK_EE_OTHER               32938
#define ID_SPIN_PAGE                    32940
#define ID_BUTTON_TRACK_COLOR           32941
#define ID_BUTTON_TRACK_FILL            32942
#define ID_COPY_PAGE1                   32943
#define ID_COPY_PAGE2                   32944
#define ID_COPY_PAGE3                   32945
#define ID_COPY_PAGE4                   32946
#define ID_COPY_PAGE5                   32947
#define ID_COPY_PAGE6                   32948
#define ID_COPY_PAGE7                   32949
#define ID_COPY_PAGE8                   32950
#define ID_COPY_PAGE9                   32951
#define ID_COPY_PAGE10                  32952
#define ID_COPY_PAGE11                  32953
#define ID_COPY_PAGE12                  32954
#define ID_COPY_PAGE13                  32955
#define ID_COPY_PAGE14                  32956
#define ID_COPY_PAGE15                  32957
#define ID_COPY_PAGE16                  32958
#define ID_COPY_PAGE17                  32959
#define ID_COPY_PAGE18                  32960
#define ID_COPY_PAGE19                  32961
#define ID_COPY_PAGE20                  32962
#define ID_COPY_PAGE99                  33041
#define ID_INDICATOR_TRK                59200
#define ID_VIEW_OUTPUT                  59394

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        319
#define _APS_NEXT_COMMAND_VALUE         32944
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           317
#endif
#endif
