
#line 3 "<stdout>"

#define COLOR_SYNTAX_HIGHLIGHT 1
#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE csh_restart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via csh_restart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void csh_restart (FILE *input_file ,yyscan_t yyscanner );
void csh__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE csh__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void csh__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void csh__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void csh_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void csh_pop_buffer_state (yyscan_t yyscanner );

static void csh_ensure_buffer_stack (yyscan_t yyscanner );
static void csh__load_buffer_state (yyscan_t yyscanner );
static void csh__init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER csh__flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE csh__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE csh__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE csh__scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *csh_alloc (yy_size_t ,yyscan_t yyscanner );
void *csh_realloc (void *,yy_size_t ,yyscan_t yyscanner );
void csh_free (void * ,yyscan_t yyscanner );

#define yy_new_buffer csh__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        csh_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            csh__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        csh_ensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            csh__create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define csh_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 91
#define YY_END_OF_BUFFER 92
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[292] =
    {   0,
        0,    0,   92,   91,   90,    2,    3,   91,    4,   70,
       62,   64,   61,   91,   87,   91,   65,   54,   63,   53,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   68,   69,   88,
       88,   88,   66,   67,   90,    1,    0,    9,    8,    0,
        4,   57,   87,   60,   56,   44,   58,   87,   87,    7,
        7,    0,    0,   45,   51,   48,   55,   59,   47,   50,
        0,   88,   88,   22,   88,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   26,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,

       88,   88,   88,    8,   43,   42,   87,    7,    0,    7,
        7,    7,    0,    0,    6,    5,    0,   46,    0,   49,
       89,   88,   88,   88,   32,   88,   88,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   10,   88,   88,   88,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   27,
       88,   88,   88,    7,    7,    6,    5,    0,    7,    5,
       52,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,   29,   88,   23,   19,   88,   36,   88,   88,
       18,   88,   28,   88,   88,   88,   88,   88,   88,   18,
       88,    7,    6,    5,    7,   88,   17,   88,   88,   88,

       88,   88,   88,   88,   88,   88,   88,   88,   12,   88,
       25,   88,   88,   40,   88,   88,   17,    0,    0,    0,
        0,   88,    5,   88,   24,   88,   88,   88,   88,   88,
       88,   88,   88,   34,   88,   88,   88,   35,   88,   33,
        0,    0,   76,   72,   71,   74,   73,   88,   88,   37,
       88,   88,   88,   88,   38,   88,   11,   16,   88,   88,
       88,   75,   78,   77,   88,   30,   88,   13,   88,   14,
       39,   20,   41,   21,   21,   88,   15,    0,    0,    0,
        0,   85,   31,   80,   79,   83,   82,   81,   86,   84,
        0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    1,    1,
        1,    7,    8,    9,   10,   11,    1,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   13,   14,   15,
       16,   17,    1,    1,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
       27,   34,   35,   36,   37,   38,   39,   27,   40,   27,
       41,   42,   43,    1,   27,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   27,   53,   54,   55,   56,
       57,   58,   27,   59,   60,   61,   62,   63,   64,   27,
       65,   27,   66,    1,   67,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[68] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        4,    5,    1,    6,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        6,    1,    1,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    6,    1
    } ;

static yyconst flex_int16_t yy_base[304] =
    {   0,
        0,    0,  761,  860,  758,  860,  753,   65,    0,  860,
       63,  860,   64,  740,   61,   75,  860,   68,   70,  733,
       77,   71,   80,   79,   78,   82,  709,   94,   84,  108,
      113,  104,   92,  122,  129,  142,  138,  860,  860,  140,
      156,  161,  860,  860,  711,  860,  188,  860,  860,  194,
        0,  860,   87,  860,  696,  860,  672,  670,  146,  638,
      161,  207,  175,  662,  661,  660,  860,  860,  860,  860,
      249,  638,  165,  637,  174,  196,  184,  193,  224,  213,
      214,  256,  222,  228,  259,  154,  261,  264,  265,  266,
      268,  272,  269,  267,  277,  274,  273,  278,  284,  283,

      299,  287,  310,  335,  860,  860,  628,  590,    0,  588,
      309,  343,    0,  349,  860,  860,  355,  860,  597,  860,
      860,  600,  324,  286,  599,  325,  338,  344,  352,  351,
      356,  354,  367,  370,  359,  355,  575,  363,  383,  389,
      392,  400,  391,  393,  407,  408,  395,  414,  412,  574,
      415,  418,  422,  540,  459,  538,  533,  442,  494,  466,
      860,  417,  423,  430,  443,  449,  456,  468,  461,  463,
      471,  466,  524,  478,  522,  519,  475,  498,  483,  485,
      492,  476,  488,  495,  496,  493,  500,  512,  506,  532,
      518,  546,  439,  551,  558,  527,  448,  535,  546,  553,

      555,  556,  557,  562,  563,  565,  567,  579,  433,  572,
      427,  570,  596,  426,  593,  597,  617,  372,  369,  650,
      355,  624,  633,  607,  330,  635,  631,  630,  662,  661,
      673,  665,  674,  322,  675,  689,  678,  314,  691,  312,
      228,  221,  220,  860,  860,  860,  860,  692,  697,  221,
      694,  670,  707,  711,  211,  717,  208,  206,  714,  719,
      723,  860,  860,  860,  729,  203,  733,  168,  716,  160,
      130,  120,  110,   99,  738,  731,   97,   96,  210,   85,
      212,   77,   81,  860,  860,  860,  860,  860,  860,  860,
      860,  794,  800,  806,  808,  813,  818,  823,  829,  835,

      841,  847,  853
    } ;

static yyconst flex_int16_t yy_def[304] =
    {   0,
      291,    1,  291,  291,  291,  291,  291,  292,  293,  291,
      291,  291,  291,  291,  291,  294,  291,  291,  291,  291,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  291,  291,  295,
      295,  295,  291,  291,  291,  291,  292,  291,  291,  292,
      293,  291,  291,  291,  291,  291,  291,  291,  291,  296,
      297,  298,  294,  291,  291,  291,  291,  291,  291,  291,
      299,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,

      295,  295,  295,  292,  291,  291,  291,  296,  300,  296,
      297,  301,  302,  298,  291,  291,  298,  291,  291,  291,
      291,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  296,  301,  296,  296,  303,  296,  298,
      291,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  301,  296,  301,  301,  295,  295,  295,  295,  295,

      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  291,  291,  299,
      291,  295,  301,  295,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      291,  291,  291,  291,  291,  291,  291,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  295,
      295,  291,  291,  291,  295,  295,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  291,  291,  220,
      291,  291,  295,  291,  291,  291,  291,  291,  291,  291,
        0,  291,  291,  291,  291,  291,  291,  291,  291,  291,

      291,  291,  291
    } ;

static yyconst flex_int16_t yy_nxt[928] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   27,   27,   27,   29,   30,
       31,   27,   32,   33,   34,   35,   27,   36,   27,   37,
       38,    4,   39,   21,   40,   23,   24,   25,   26,   27,
       28,   27,   27,   29,   30,   31,   27,   41,   33,   34,
       35,   27,   42,   27,   37,   43,   44,   48,   48,   49,
       52,   58,   59,   55,   53,   53,   61,   64,   54,   62,
       56,   71,   65,   66,   67,   68,   69,   71,   71,   71,
       71,   71,   71,  290,   71,  287,   73,   58,   59,   75,

       79,   77,   71,  284,   71,   85,   50,   71,   80,   71,
       76,   78,   74,   81,   71,   82,   63,   93,   71,   83,
       71,   91,   73,   71,   75,   86,   79,   77,   84,   92,
       71,   85,   71,   80,   88,   76,   78,   74,   81,   71,
       71,   82,   87,   93,   89,   83,   94,   91,   71,   90,
       71,   86,   71,   84,   97,   92,   58,   59,   95,  100,
       88,   96,  111,   98,   71,  112,   71,   87,   75,   89,
       71,   71,   94,   91,   90,   71,   99,  291,   71,   76,
       97,   92,   98,   95,   71,  100,   96,  136,   60,   98,
       48,   48,   49,  101,   71,   99,   48,   48,  104,   91,

      123,   99,  113,   71,   76,  124,   71,  102,  103,  115,
      115,  116,  136,   71,  126,   60,   71,  125,   71,  285,
       99,   71,  127,   71,   71,  123,  286,  288,  289,   50,
      124,   71,   71,  130,   71,   50,  264,  263,   71,  126,
       60,  128,  133,  125,  262,  131,  129,  127,  117,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  130,
      134,  121,  121,  121,  121,  121,   71,  128,  133,   71,
      131,   71,  129,  132,   71,   71,   71,   71,   71,   71,
      137,  135,   71,   71,   71,  134,  140,   71,   71,  121,
      121,  121,  143,   71,   71,  145,   71,   71,  144,  132,

      139,  141,  138,  146,  142,  163,  137,  135,  147,   71,
      111,  148,  140,  112,  121,  121,  149,  150,  143,  142,
       71,  145,   71,  144,   71,  139,  141,  138,  146,  142,
      124,  163,   71,  147,   71,   71,  148,   48,   48,   49,
       71,  149,  150,  148,  152,  156,  156,  157,   71,  162,
      113,  115,  115,  116,   71,  151,  114,  115,  115,  160,
      164,   71,   71,  166,   71,   71,   71,  165,  153,   71,
      247,  167,  168,   71,  172,  162,   50,   71,  245,  244,
       71,  170,  176,  114,  158,  164,  169,  174,  173,  166,
      117,  171,  165,   71,  175,  177,  117,  167,  168,   71,

      172,   71,   71,   71,  178,   71,  170,  176,  114,  180,
       71,  169,  179,  174,  173,  182,  171,   71,   71,  175,
      177,  181,   71,  186,   71,   71,  185,   71,   71,  188,
      178,  183,   71,   71,  163,  180,   71,   71,  179,  181,
       71,  182,  184,   71,  115,  193,  194,  181,  186,  187,
      197,  198,  185,   71,  196,  188,  183,  187,   71,   71,
      189,  156,  156,  157,  199,  190,   71,  184,  115,  115,
      116,   71,  114,   71,  187,  197,   71,  198,   71,  196,
      109,   71,  191,  195,  200,   71,   71,  201,   71,  202,
      199,  206,  208,   71,  204,   71,  203,  207,   71,  114,

      158,  205,   71,   71,  209,   71,   71,  117,   71,  200,
       71,  211,  201,  210,  214,  202,   71,  206,  208,  204,
      212,  203,   71,  207,  114,  215,  205,  213,   71,   71,
      209,  216,   71,  197,   71,  109,  211,   71,  210,  218,
      214,  219,  220,  215,  224,   71,  212,  221,  156,  156,
      157,  215,  213,  156,  156,  157,   71,  216,  217,  114,
      156,  156,  223,   71,  114,   71,   71,   71,  225,  222,
      224,  114,   71,   71,  109,   71,  226,   71,  227,  109,
       71,  109,   71,  228,   71,   71,  114,  158,  234,   71,
      229,  114,  158,  225,  232,  233,  230,  231,  114,  158,

      236,  226,  235,   71,  227,  237,   71,   71,  228,   71,
       71,  114,  239,  161,  234,  229,  114,   71,  240,  232,
      233,  230,  231,  114,  238,  236,  241,   71,  235,  109,
      237,  109,  242,  243,   71,  156,  156,  157,  239,  107,
       71,   71,  249,  239,  240,   71,  114,   71,   71,  238,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      246,  252,  121,  121,  121,  121,  121,  249,  251,  248,
      250,   71,   71,  114,  158,   71,  120,  119,  118,  109,
       71,  107,  106,   71,   71,   71,  252,  253,   71,  254,
      121,  121,  121,  251,  255,  250,  258,  257,  114,   71,

      256,   71,   71,  268,   71,  105,  260,   71,  261,  261,
      259,  267,   45,  253,  254,  121,  121,   71,  266,   71,
      255,   71,  258,  257,   71,  256,   71,   71,  268,   71,
      269,  260,  270,   71,  261,  265,  259,  267,  271,   71,
      273,   71,  272,   71,  266,  278,  277,  279,  280,   70,
       57,  274,  283,  281,  282,   46,  269,  274,  270,   45,
      291,  291,  291,  291,  271,  291,  273,  272,  276,  291,
      291,  277,  291,  291,  291,  291,  274,  291,  283,  291,
      291,  291,  275,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  276,   47,   47,   47,   47,   47,   47,

       51,  291,  291,   51,   51,   51,   60,   60,   60,   60,
       60,   72,   72,  108,  108,  108,  108,  108,  110,  110,
      110,  110,  110,  114,  114,  114,  114,  114,  114,  122,
      122,  122,  291,  122,  122,  154,  291,  154,  154,  154,
      154,  155,  155,  155,  155,  155,  155,  159,  291,  159,
      159,  159,  159,  192,  192,  192,  192,  192,  192,    3,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,

      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291
    } ;

static yyconst flex_int16_t yy_chk[928] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    8,    8,    8,
       11,   15,   15,   13,   11,   13,   16,   18,   11,   16,
       13,   22,   18,   18,   18,   19,   19,   21,   25,   24,
       23,  283,   26,  282,   29,  280,   21,   53,   53,   22,

       24,   23,   33,  278,   28,   29,    8,  277,   25,  274,
       22,   23,   21,   26,   32,   28,   16,   33,   30,   28,
      273,   32,   21,   31,   22,   30,   24,   23,   28,   32,
      272,   29,   34,   25,   31,   22,   23,   21,   26,   35,
      271,   28,   30,   33,   31,   28,   34,   32,   37,   31,
       40,   30,   36,   28,   35,   32,   59,   59,   34,   37,
       31,   34,   61,   36,   86,   61,   41,   30,   40,   31,
      270,   42,   34,   41,   31,   73,   36,   63,  268,   40,
       35,   41,   42,   34,   75,   37,   34,   86,   63,   36,
       47,   47,   47,   40,   77,   42,   50,   50,   50,   41,

       73,   36,   61,   78,   40,   75,   76,   41,   42,   62,
       62,   62,   86,  266,   77,   63,  258,   76,  257,  279,
       42,  255,   78,   80,   81,   73,  279,  281,  281,   47,
       75,  250,   83,   80,   79,   50,  243,  242,   84,   77,
       63,   79,   83,   76,  241,   81,   79,   78,   62,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   80,
       84,   71,   71,   71,   71,   71,   82,   79,   83,   85,
       81,   87,   79,   82,   88,   89,   90,   94,   91,   93,
       87,   85,   92,   97,   96,   84,   90,   95,   98,   71,
       71,   71,   93,  100,   99,   95,  124,  102,   94,   82,

       89,   91,   88,   96,   92,  124,   87,   85,   97,  101,
      111,   98,   90,  111,   71,   71,   99,  100,   93,  102,
      103,   95,  240,   94,  238,   89,   91,   88,   96,   92,
      101,  124,  234,   97,  123,  126,   98,  104,  104,  104,
      225,   99,  100,  103,  102,  112,  112,  112,  127,  123,
      111,  114,  114,  114,  128,  101,  112,  117,  117,  117,
      126,  130,  129,  128,  132,  136,  131,  127,  103,  135,
      221,  129,  129,  138,  132,  123,  104,  133,  219,  218,
      134,  130,  136,  112,  112,  126,  129,  134,  133,  128,
      114,  131,  127,  139,  135,  138,  117,  129,  129,  140,

      132,  143,  141,  144,  139,  147,  130,  136,  112,  141,
      142,  129,  140,  134,  133,  143,  131,  145,  146,  135,
      138,  142,  149,  147,  148,  151,  146,  162,  152,  149,
      139,  144,  153,  163,  151,  141,  214,  211,  140,  152,
      164,  143,  145,  209,  158,  158,  158,  142,  147,  148,
      163,  164,  146,  165,  162,  149,  144,  153,  197,  166,
      151,  155,  155,  155,  165,  152,  167,  145,  160,  160,
      160,  169,  155,  170,  148,  163,  172,  164,  168,  162,
      193,  171,  153,  158,  166,  177,  182,  167,  174,  168,
      165,  172,  177,  179,  170,  180,  169,  174,  183,  155,

      155,  171,  181,  186,  179,  184,  185,  160,  178,  166,
      187,  182,  167,  180,  186,  168,  189,  172,  177,  170,
      184,  169,  188,  174,  155,  187,  171,  185,  191,  176,
      179,  188,  175,  189,  173,  159,  182,  196,  180,  190,
      186,  190,  190,  191,  196,  198,  184,  190,  192,  192,
      192,  187,  185,  194,  194,  194,  199,  188,  189,  192,
      195,  195,  195,  200,  194,  201,  202,  203,  198,  191,
      196,  195,  204,  205,  157,  206,  199,  207,  200,  156,
      212,  154,  210,  201,  150,  137,  192,  192,  207,  208,
      202,  194,  194,  198,  205,  206,  203,  204,  195,  195,

      210,  199,  208,  215,  200,  212,  213,  216,  201,  125,
      122,  192,  215,  119,  207,  202,  194,  224,  216,  205,
      206,  203,  204,  195,  213,  210,  217,  217,  208,  110,
      212,  108,  217,  217,  222,  223,  223,  223,  215,  107,
      228,  227,  224,  222,  216,  226,  223,   74,   72,  213,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  228,  220,  220,  220,  220,  220,  224,  227,  222,
      226,  230,  229,  223,  223,  232,   66,   65,   64,   60,
      252,   58,   57,  231,  233,  235,  228,  229,  237,  230,
      220,  220,  220,  227,  231,  226,  235,  233,  223,  236,

      232,  239,  248,  252,  251,   55,  237,  249,  239,  248,
      236,  251,   45,  229,  230,  220,  220,  253,  249,   27,
      231,  254,  235,  233,  259,  232,  269,  256,  252,  260,
      253,  237,  254,  261,  239,  248,  236,  251,  256,  265,
      260,  276,  259,  267,  249,  275,  269,  275,  275,   20,
       14,  261,  276,  275,  275,    7,  253,  265,  254,    5,
        3,    0,    0,    0,  256,    0,  260,  259,  267,    0,
        0,  269,    0,    0,    0,    0,  261,    0,  276,    0,
        0,    0,  265,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  267,  292,  292,  292,  292,  292,  292,

      293,    0,    0,  293,  293,  293,  294,  294,  294,  294,
      294,  295,  295,  296,  296,  296,  296,  296,  297,  297,
      297,  297,  297,  298,  298,  298,  298,  298,  298,  299,
      299,  299,    0,  299,  299,  300,    0,  300,  300,  300,
      300,  301,  301,  301,  301,  301,  301,  302,    0,  302,
      302,  302,  302,  303,  303,  303,  303,  303,  303,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,

      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      291,  291,  291,  291,  291,  291,  291
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "language2.ll"
#line 5 "language2.ll"
/*
    This file is part of Msc-generator.
    Copyright 2008,2009,2010,2011,2012 Zoltan Turanyi
    Distributed under GNU Affero General Public License.

    Msc-generator is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Msc-generator is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with Msc-generator.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifdef COLOR_SYNTAX_HIGHLIGHT
#define C_S_H (1)
#define C_S_H_IS_COMPILED
#else
#define C_S_H (0)
#endif

#include <stdio.h>
#include <string.h>
#include <iostream>

#ifdef C_S_H_IS_COMPILED
#include "csh.h"
#define YYMSC_RESULT_TYPE Csh
#define RESULT csh

//If we scan for color syntax highlight use this location
//yyerror is defined by bison, the other is defined for flex
#define YYLTYPE_IS_DECLARED
#define YYLTYPE CshPos
#define CHAR_IF_CSH(A) char

#include "colorsyntax.h"
#include "language_misc.h"
#include "commands.h" //MSC_* defs and CommandNote
#else
#include "msc.h"
#define YYMSC_RESULT_TYPE Msc
#define RESULT msc

#define CHAR_IF_CSH(A) A
#include "language.h"
#include "language_misc.h"
#endif

#ifdef C_S_H_IS_COMPILED

#define YY_INPUT(buffer, res, max_size)             \
do {                                                \
    parse_parm *pp = csh_get_extra(yyscanner);        \
    if (pp->pos >= pp->length)                      \
        res = YY_NULL;                              \
    else                                            \
    {                                               \
        res = pp->length - pp->pos;                 \
        res > (int)max_size ? res = max_size : 0;   \
        memcpy(buffer, pp->buf + pp->pos, res);     \
        pp->pos += res;                             \
    }                                               \
} while (0)

#define YY_USER_ACTION do {                     \
    yylloc->first_pos = yylloc->last_pos+1;     \
    yylloc->last_pos = yylloc->last_pos+yyleng; \
    } while(0);

#define YYRHSLOC(Rhs, K) ((Rhs)[K])

#define YYLLOC_DEFAULT(Current, Rhs, N)				\
    do								\
      if (YYID (N))                                             \
	{							\
	  (Current).first_pos = YYRHSLOC (Rhs, 1).first_pos;	\
	  (Current).last_pos  = YYRHSLOC (Rhs, N).last_pos;	\
	}							\
      else							\
	{							\
        (Current).first_pos = (Current).last_pos   =		\
	    YYRHSLOC (Rhs, 0).last_pos;				\
	}							\
    while (YYID (0))

#else

//Read in 512-byte chunks
//We use this low value to make progress reporint more frequent
#define YY_READ_BUF_SIZE 512

#define YY_INPUT(buffer, res, max_size)             \
do {                                                \
    parse_parm *pp = csh_get_extra(yyscanner);        \
    if (pp->pos >= pp->length)                      \
        res = YY_NULL;                              \
    else                                            \
    {                                               \
        res = pp->length - pp->pos;                 \
        res > (int)max_size ? res = max_size : 0;   \
        memcpy(buffer, pp->buf + pp->pos, res);     \
		pp->msc->Progress.DoneItem(MscProgress::PARSE, res); \
        pp->pos += res;                             \
    }                                               \
} while (0)

#define YY_USER_ACTION do {                              \
    yylloc->first_line = yylloc->last_line;              \
    yylloc->first_column = yylloc->last_column+1;        \
    yylloc->last_column = yylloc->first_column+yyleng-1; \
    } while(0);

#include "parse_tools.h"

#endif /* C_S_H_IS_COMPILED */

#line 870 "<stdout>"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r

    #    define yylloc yyg->yylloc_r

int csh_lex_init (yyscan_t* scanner);

int csh_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int csh_lex_destroy (yyscan_t yyscanner );

int csh_get_debug (yyscan_t yyscanner );

void csh_set_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE csh_get_extra (yyscan_t yyscanner );

void csh_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *csh_get_in (yyscan_t yyscanner );

void csh_set_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *csh_get_out (yyscan_t yyscanner );

void csh_set_out  (FILE * out_str ,yyscan_t yyscanner );

int csh_get_leng (yyscan_t yyscanner );

char *csh_get_text (yyscan_t yyscanner );

int csh_get_lineno (yyscan_t yyscanner );

void csh_set_lineno (int line_number ,yyscan_t yyscanner );

YYSTYPE * csh_get_lval (yyscan_t yyscanner );

void csh_set_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

       YYLTYPE *csh_get_lloc (yyscan_t yyscanner );

        void csh_set_lloc (YYLTYPE * yylloc_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int csh_wrap (yyscan_t yyscanner );
#else
extern int csh_wrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

int csh_lex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param ,yyscan_t yyscanner);

#define YY_DECL int csh_lex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 129 "language2.ll"


 /* Newline characters in all forms accepted */
#line 1118 "<stdout>"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			csh_ensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				csh__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		csh__load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 292 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 860 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 132 "language2.ll"

  #ifndef C_S_H_IS_COMPILED
    msc_jump_line(yylloc);
  #endif

	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 138 "language2.ll"

  #ifndef C_S_H_IS_COMPILED
    msc_jump_line(yylloc);
  #endif

	YY_BREAK
case 3:
YY_RULE_SETUP
#line 144 "language2.ll"

  #ifndef C_S_H_IS_COMPILED
    msc_jump_line(yylloc);
  #endif

	YY_BREAK
/* # starts a comment last until end of line */
case 4:
YY_RULE_SETUP
#line 151 "language2.ll"

  #ifdef C_S_H_IS_COMPILED
    csh_get_extra(yyscanner)->csh->AddCSH(*yylloc, COLOR_COMMENT);
  #endif

	YY_BREAK
/* This is a colon-quoted string, finished by a quotation mark
 ** : "<string>"
 ** <string> can contain escaped quotation marks, but no line breaks
 */
case 5:
YY_RULE_SETUP
#line 162 "language2.ll"

  #ifdef C_S_H_IS_COMPILED
    yylval_param->str = strdup(yytext);
  #else
    {
    /* after whitespaces we are guaranteed to have a tailing and heading quot */
    char *s = msc_remove_head_tail_whitespace(yytext+1);
    /* s now points to the heading quotation marks.
    ** Now get rid of both quotation marks */
    std::string str(s+1);
    str.erase(str.length()-1);
    /* Calculate the position of the string and prepend a location escape */
    FileLineCol pos(csh_get_extra(yyscanner)->msc->current_file,
                 yylloc->first_line, yylloc->first_column + unsigned(s+1 - yytext));
    yylval_param->str = strdup((pos.Print() + str).c_str());
    }
  #endif
    return TOK_COLON_QUOTED_STRING;

	YY_BREAK
/* This is a colon-quoted string, finished by a newline (trailing context)
 ** : "<string>$
 ** <string> can contain escaped quotation marks, but no line breaks
 */
case 6:
/* rule 6 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 186 "language2.ll"

  #ifdef C_S_H_IS_COMPILED
    yylval_param->str = strdup(yytext);
  #else
    {
    /* after whitespaces we are guaranteed to have a heading quot */
    const char *s = msc_remove_head_tail_whitespace(yytext+1);
    // s now points to heading quotation mark
    FileLineCol pos(csh_get_extra(yyscanner)->msc->current_file,
                 yylloc->first_line, yylloc->first_column + unsigned(s - yytext));
    csh_get_extra(yyscanner)->msc->Error.Error(pos,
         "This opening quotation mark misses its closing pair. "
         "Assuming string termination at line-end.",
         "Quoted strings cannot have line breaks. Use \'\\n\' to insert a line break.");
    /* Advance pos beyond the leading quotation mark */
    pos.col++;
    yylval_param->str = strdup((pos.Print() + (s+1)).c_str());
    }
  #endif
    return TOK_COLON_QUOTED_STRING;

	YY_BREAK
/* This is a non quoted colon-string
 ** : <string>
 ** terminated by any of: quot mark, backslash [ { or ;
 ** Honors escaping of the above via a backslash
 ** Can contain quotation marks (escaped or unescaped), but can not start with it
 */
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 214 "language2.ll"

  #ifdef C_S_H_IS_COMPILED
    yylval_param->str = strdup(yytext);
  #else
    yylval_param->str = msc_process_colon_string(yytext, yylloc,
                        csh_get_extra(yyscanner)->msc->current_file);
  #endif
    return TOK_COLON_STRING;

	YY_BREAK
/* A simple quoted string, that can have escaped quotation marks inside.*/
case 8:
YY_RULE_SETUP
#line 225 "language2.ll"

    yylval_param->str = strdup(yytext+1);
    yylval_param->str[strlen(yylval_param->str) - 1] = '\0';
    return TOK_QSTRING;

	YY_BREAK
/* A simple quoted string, missing a closing quotation mark */
case 9:
/* rule 9 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 232 "language2.ll"

  #ifdef C_S_H_IS_COMPILED
    yylval_param->str = strdup(yytext+1);
  #else
    {
    yylval_param->str = strdup(yytext+1);
    FileLineCol pos(csh_get_extra(yyscanner)->msc->current_file,
                 yylloc->first_line, yylloc->first_column);
    csh_get_extra(yyscanner)->msc->Error.Error(pos,
         "This opening quotation mark misses its closing pair. "
         "Assuming string termination at line-end.",
         "Quoted strings cannot have line breaks. Use \'\\n\' to insert a line break.");
    }
  #endif
    return TOK_QSTRING;

	YY_BREAK
/* These keywords are case insensitive */
case 10:
YY_RULE_SETUP
#line 250 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_MSC;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 251 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_HEADING;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 252 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_NUDGE;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 253 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_DEFCOLOR;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 254 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_DEFSTYLE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 255 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_DEFDESIGN;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 256 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_NEWPAGE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 257 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_BIG;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 258 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_PIPE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 259 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_MARK;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 260 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_PARALLEL;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 261 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_VERTICAL;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 262 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_AT;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 263 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_AT_POS;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 264 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_AT_POS;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 265 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_AT_POS;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 266 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_BOOLEAN;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 267 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_BOOLEAN;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 268 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_SHOW;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 269 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_HIDE;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 270 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_ACTIVATE;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 271 "language2.ll"
yylval_param->str= strdup(yytext); return TOK_DEACTIVATE;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 272 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_BYE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 273 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_VSPACE;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 274 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_HSPACE;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 275 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_SYMBOL;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 276 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_NOTE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 277 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_COMMENT;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 278 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_ENDNOTE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 279 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_FOOTNOTE;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 280 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_TITLE;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 281 "language2.ll"
yylval_param->str = strdup(yytext); return TOK_COMMAND_SUBTITLE;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 283 "language2.ll"
yylval_param->arctype=MSC_ARC_DISCO;       return TOK_SPECIAL_ARC;      // ...
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 284 "language2.ll"
yylval_param->arctype=MSC_ARC_DIVIDER;     return TOK_SPECIAL_ARC;      // ---
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 285 "language2.ll"
yylval_param->arctype=MSC_ARC_SOLID;       return TOK_REL_SOLID_TO;     // ->
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 286 "language2.ll"
yylval_param->arctype=MSC_ARC_SOLID;       return TOK_REL_SOLID_FROM;   // <-
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 287 "language2.ll"
yylval_param->arctype=MSC_ARC_SOLID_BIDIR; return TOK_REL_SOLID_BIDIR;  // <->
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 288 "language2.ll"
yylval_param->arctype=MSC_ARC_DOUBLE;      return TOK_REL_DOUBLE_TO;    // =>
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 289 "language2.ll"
yylval_param->arctype=MSC_ARC_DOUBLE;      return TOK_REL_DOUBLE_FROM;  // <=
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 290 "language2.ll"
yylval_param->arctype=MSC_ARC_DOUBLE_BIDIR;return TOK_REL_DOUBLE_BIDIR; // <=>
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 291 "language2.ll"
yylval_param->arctype=MSC_ARC_DASHED;      return TOK_REL_DASHED_TO;    // >>
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 292 "language2.ll"
yylval_param->arctype=MSC_ARC_DASHED;      return TOK_REL_DASHED_FROM;  // <<
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 293 "language2.ll"
yylval_param->arctype=MSC_ARC_DASHED_BIDIR;return TOK_REL_DASHED_BIDIR; // <<>>
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 294 "language2.ll"
yylval_param->arctype=MSC_ARC_DOTTED;      return TOK_REL_DOTTED_TO;    // >
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 295 "language2.ll"
yylval_param->arctype=MSC_ARC_DOTTED;      return TOK_REL_DOTTED_FROM;  // <
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 296 "language2.ll"
yylval_param->arctype=MSC_ARC_DOTTED_BIDIR;return TOK_REL_DOTTED_BIDIR; // <>
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 297 "language2.ll"
yylval_param->arctype=MSC_BOX_SOLID;       return TOK_EMPH;             // --
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 298 "language2.ll"
yylval_param->arctype=MSC_BOX_DASHED;      return TOK_EMPH;             // ++
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 299 "language2.ll"
yylval_param->arctype=MSC_BOX_DOTTED;      return TOK_EMPH;             // ..
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 300 "language2.ll"
yylval_param->arctype=MSC_BOX_DOUBLE;      return TOK_EMPH;             // ==
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 301 "language2.ll"
return TOK_PLUS_EQUAL;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 302 "language2.ll"
return TOK_DASH;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 303 "language2.ll"
return TOK_PLUS;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 304 "language2.ll"
return TOK_EQUAL;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 305 "language2.ll"
return TOK_COMMA;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 306 "language2.ll"
return TOK_SEMICOLON;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 307 "language2.ll"
return TOK_OCBRACKET;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 308 "language2.ll"
return TOK_CCBRACKET;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 309 "language2.ll"
return TOK_OSBRACKET;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 310 "language2.ll"
return TOK_CSBRACKET;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 311 "language2.ll"
return TOK_ASTERISK;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 313 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 314 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 315 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 316 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 317 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 318 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 319 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 320 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 321 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 322 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 323 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 324 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 325 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 326 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 327 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 328 "language2.ll"
yylval_param->str=strdup(yytext); return TOK_STYLE_NAME;
	YY_BREAK
/* Numbers */
case 87:
YY_RULE_SETUP
#line 331 "language2.ll"

    yylval_param->str = strdup(yytext);
    return TOK_NUMBER;

	YY_BREAK
/* Strings not ending with a dot */
case 88:
YY_RULE_SETUP
#line 337 "language2.ll"

    yylval_param->str = strdup(yytext);
    return TOK_STRING;

	YY_BREAK
/* Strings ending with a dot, not followed by a second dot */
case 89:
/* rule 89 can match eol */
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 343 "language2.ll"

    yylval_param->str = strdup(yytext);
    return TOK_STRING;

	YY_BREAK
case 90:
YY_RULE_SETUP
#line 348 "language2.ll"
/* ignore whitespace */;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 349 "language2.ll"
ECHO;
	YY_BREAK
#line 1786 "<stdout>"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * csh_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( csh_wrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of csh_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					csh_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			csh_restart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) csh_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 292 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 292 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 291);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					csh_restart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( csh_wrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void csh_restart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        csh_ensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            csh__create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	csh__init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	csh__load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void csh__switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		csh_pop_buffer_state();
	 *		csh_push_buffer_state(new_buffer);
     */
	csh_ensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	csh__load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (csh_wrap()) processing, but the only time this flag
	 * is looked at is after csh_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void csh__load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE csh__create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) csh_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in csh__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) csh_alloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in csh__create_buffer()" );

	b->yy_is_our_buffer = 1;

	csh__init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with csh__create_buffer()
 * @param yyscanner The scanner object.
 */
    void csh__delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		csh_free((void *) b->yy_ch_buf ,yyscanner );

	csh_free((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a csh_restart() or at EOF.
 */
    static void csh__init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	csh__flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then csh__init_buffer was _probably_
     * called from csh_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void csh__flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		csh__load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void csh_push_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	csh_ensure_buffer_stack(yyscanner);

	/* This block is copied from csh__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from csh__switch_to_buffer. */
	csh__load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void csh_pop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	csh__delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		csh__load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void csh_ensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)csh_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in csh_ensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)csh_realloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in csh_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE csh__scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) csh_alloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in csh__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	csh__switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to csh_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       csh__scan_bytes() instead.
 */
YY_BUFFER_STATE csh__scan_string (yyconst char * yystr , yyscan_t yyscanner)
{

	return csh__scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to csh_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE csh__scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) csh_alloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in csh__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = csh__scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in csh__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE csh_get_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int csh_get_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;

    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int csh_get_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;

    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *csh_get_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *csh_get_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int csh_get_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *csh_get_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void csh_set_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void csh_set_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "csh_set_lineno called with no buffer" , yyscanner);

    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void csh_set_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "csh_set_column called with no buffer" , yyscanner);

    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see csh__switch_to_buffer
 */
void csh_set_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void csh_set_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int csh_get_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void csh_set_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * csh_get_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void csh_set_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *csh_get_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}

void csh_set_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}

/* User-visible API */

/* csh_lex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int csh_lex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) csh_alloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* csh_lex_init_extra has the same functionality as csh_lex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to csh_alloc in
 * the yyextra field.
 */

int csh_lex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    csh_set_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) csh_alloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    csh_set_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from csh_lex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * csh_lex_init()
     */
    return 0;
}

/* csh_lex_destroy is for both reentrant and non-reentrant scanners. */
int csh_lex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		csh__delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		csh_pop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	csh_free(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        csh_free(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * csh_lex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    csh_free ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *csh_alloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *csh_realloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void csh_free (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see csh_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 349 "language2.ll"



/* END OF FILE */

